/*
let elem = document.querySelector('#elem');

elem.addEventListener('focus', function one() {
	console.log('34')
});
elem.addEventListener('blur', function two() {
	console.log('90')
})

let elem2 = document.querySelector('#elem2');

elem2.addEventListener('blur', function wer() {
	alert(Math.pow(elem2.value, 2))
});

let elem3 = document.querySelector('#elem3');

elem3.addEventListener('focus', function ppp(){
	elem3.removeAttribute('value', 'text')
});
*/

/*
let elem = document.querySelector('#elem');

elem.addEventListener('focus', function hjk(){
	elem.remoteAttribute('value')
});
*/

let elem = document.querySelector('#elem');

elem.addEventListener()